function sendMarker(io,marker,equipment, EPSILON)
%sendMarker Sends markers to BrainVision Recorder
%   After generating an 'io' structure using the enablePort function
%   send marker to BrainVision Recorder or cognionics with value marker
%
%   io - input/output io64 object generated by enablePort function
%   marker - value of marker (must be an integer)
%   EPSILON - time duration of marker. Generally set to be a small number
%   (atleast 1/sampling frequency).
if strcmp(equipment,'acticap')
    io64(io.obj,io.address,uint32(marker));   %output command
    pause(EPSILON); %must pause a minimum of 1 time sample
    disp(sprintf('Sent marker %s',char(marker)));
    data_in = io64(io.obj,io.address);
    disp([num2str(data_in) ' Read from Parallel port']);
    io64(io.obj,io.address, 0);
    pause(EPSILON);
elseif strcmp(equipment,'cognionics')
    fwrite(io.obj, marker, 'uint8');
    pause(EPSILON);
    fwrite(io.obj, 0, 'uint8');
   disp(sprintf('Sent marker %s',char(marker)));
end

end

